# /etc/nginx/sites-available/cosmic-clock.info
# Step 1: HTTP only (certbot will add SSL)

server {
    listen 80;
    listen [::]:80;
    server_name cosmic-clock.info www.cosmic-clock.info;

    location ^~ /.well-known/acme-challenge/ {
        root /var/www/letsencrypt;
        default_type "text/plain";
        try_files $uri =404;
    }

    location / {
        proxy_pass http://127.0.0.1:3060;
        proxy_http_version 1.1;
        proxy_set_header Host               $host;
        proxy_set_header X-Real-IP          $remote_addr;
        proxy_set_header X-Forwarded-For    $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto  $scheme;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_read_timeout 600;
        proxy_send_timeout 600;
        proxy_buffering off;
    }

    access_log /var/log/nginx/cosmic_clock_info_access.log;
    error_log  /var/log/nginx/cosmic_clock_info_error.log;
}
